name: 'Chart Validation for ChartMuseum'
description: 'Validates and pushes Helm charts to ChartMuseum.'
inputs:
  chart-directory:
    description: 'Path to the chart directory'
    required: true
  chart-yaml:
    description: 'Path to the Chart.yaml file'
    required: true
  chartmuseum-url:
    description: 'URL of ChartMuseum repository'
    required: true
  chart-repo:
    description: 'Name of the chart repository'
    required: true
  chart-name:
    description: 'Name of the Helm chart'
    required: true
outputs:
  chart-validation-result:
    description: 'Validation result of the Helm chart'

runs:
  using: 'composite'
  steps:
    - name: Check current chart version
      run: |
        CURRENT_CHART_VERSION=$(grep -E '^version:' ${{ inputs.chart-yaml }} | awk '{print $2}')
        echo "Current chart version: $CURRENT_CHART_VERSION"
        echo "CURRENT_CHART_VERSION=$CURRENT_CHART_VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Add ChartMuseum repository
      run: |
        helm repo add fetch-charts ${{ inputs.chartmuseum-url }}
      shell: bash

    - name: Update helm repository
      run: helm repo update
      shell: bash

    - name: Search existing chart on ChartMuseum
      id: search_chart
      run: |
        CHART_SEARCH_RESULT=$(helm search repo ${{ inputs.chart-repo }}/${{ inputs.chart-name }} --versions -o json | jq -r ".[] | select(.version == \"$CURRENT_CHART_VERSION\")")
        if [[ ! -z $CHART_SEARCH_RESULT ]]; then
          echo "Chart version already exists on ChartMuseum. Exiting..."
          exit 1
        fi
      shell: bash

    - name: Set dynamic fields as global env
      run: |
        echo "CHART_DIRECTORY=${{ inputs.chart-directory }}" >> $GITHUB_ENV
        echo "CHART_YAML=${{ inputs.chart-yaml }}" >> $GITHUB_ENV
        echo "CHARTMUSEUM_URL=${{ inputs.chartmuseum-url }}" >> $GITHUB_ENV
        echo "CHART_REPO=${{ inputs.chart-repo }}" >> $GITHUB_ENV
        echo "CHART_NAME=${{ inputs.chart-name }}" >> $GITHUB_ENV
      shell: bash
